% Purpose: the host-workaround patches to swipl-devel itself, the set this engine refuses to boot without,
%   one host_patch(File, Sha256) fact per patch at tests/checks/host_workarounds.
% Generated by `sh tools/pymetta-host/declare-host.sh require`; the
%   host-declaration lane regenerates it and fails on any difference, so edit
%   the patches and rerun the command rather than this file.
:- module(metta_host_patches, [host_patch/2]).

host_patch('swi-bound-clause-reference-ignores-snapshot.patch', 'db9913669e65b31ac4f2a7ff4f36ccfe4bb717dbb34b136c85de00215cb9a30b').
host_patch('swi-cached-undefined-supervisor.patch', 'c04bb1d905b11effb6d6022e94beba588f42bccbab8c56d04e78e17338a2ba24').
host_patch('swi-cleanup-window.patch', '36713ed4b86659d3f67337e845bbf86786a588229593ddbe9a892bfcc1d9db5f').
host_patch('swi-concurrent-import-removal-resets-provider.patch', '4ee42ff7c13cdedf01b90cc0355b8cf1af73b6266c6a2f249b900bb30301b492').
host_patch('swi-destroyed-leader-keeps-shared-table.patch', '202f07915055aca62a360f7fb768bc346748ef7859ff227251e26ec3192b611d').
host_patch('swi-empty-indexed-snapshot.patch', '81c284a850e9d67a45f41da0b5f6772bb7ca1fbb389563a17a63a5fd28dbac12').
host_patch('swi-engine-query-offers-foreign-yield.patch', '74e3e56a4b8f79b369c03781b3d7c57089c4ccceef2c0fbc6975272dc9a7858d').
host_patch('swi-erased-definition-bypasses-loader.patch', '56bf3f614f408d1bf667e397b7f9d8e08162b38a10636e1eb3fa4baa61499fb2').
host_patch('swi-file-search-cache-sweep.patch', 'cca21f0871baa9ccd749b1c10e9a8b6fdcc8c7910c2d6494ec1cb72a523165bd').
host_patch('swi-gc-in-frame-finished-listener-clears-a-live-slot.patch', '9895191655d5d5ea8776aea08811cda4ce6d6be26803994ea8f9aa05dabb30da').
host_patch('swi-gc-signal-engineless-thread.patch', 'd127f57e851f1af353b986e5f9f25142be0b36a65e73d486dcaf882677b88e09').
host_patch('swi-halt-passes-created-thread.patch', '3bba612df049bca193ecaf0bab499fc3f447dee83b6671b5881788adff4d8c34').
host_patch('swi-heap-refusal-reported-as-stack-limit.patch', '36d9a4ee30b32e6f5cd0090e0f19d56ed45448798968cbe504f246019900dbcf').
host_patch('swi-index-built-after-erase-hides-older-views.patch', '6befd562a1518fbdffb0c27f83d21b39864d15023c5efbc4d2469bd137de23a1').
host_patch('swi-libbf-powm-unreduced.patch', '003e372224f7d0a22cf442e053d8b5d9ccf0c18ffa75a5f6fbec2d5d238e14e1').
host_patch('swi-locale-default-encoding.patch', 'f4a78676056b8fcafa64ab6b4988bddc0f1700afe90b210e94f7676b565d730c').
host_patch('swi-nested-retract-loses-outer-assert.patch', 'e07802e6a24d839288fb9805424cf583600066f129bfa15e644667902e281550').
host_patch('swi-qlf-extension-spec.patch', 'd5d4c1e2ab9df25977d53bcc497bdd286d946c41fd3d4f69285b8ec48a8dbbe6').
host_patch('swi-qlf-failed-include-source-module.patch', '00915b2e768e7eee601cc5d0acbcddd96aa1847addd591c33ec55f29f8ad0d14').
host_patch('swi-query-frame-discarded-on-engine-destroy.patch', '068f6ab5bcf8703df9292222e16663c6fc7b0df61cb52e0bcaed2926fbf9cccf').
host_patch('swi-reeval-prepare-writes-past-its-arguments.patch', 'e07f43cf7d7b3147987298b6f773cac1388a9ef46bfe5be17d1d002e50339e66').
host_patch('swi-shared-table-waits-for-owner-beneath.patch', '59e4968de7423abe5c4650d0092da472cca5c45ca9d27a511c56dec007258526').
host_patch('swi-shift-misses-pending-depart-arguments.patch', 'f24b658ebf1f3782d8f758dfb75ec42748bf2ce42a2fa032f49d1a1de2633bff').
host_patch('swi-thread-join-detach-window.patch', '418987e80776f6e69611af7912133f2398f208b3cbab5abd6209d1d4a576c192').
host_patch('swi-threadless-shared-table-private-per-engine.patch', '6619febea289bf67cb7b8c6e41be4bc7a006931ebb342a1ac2652cc4240542eb').
host_patch('swi-transaction-enumerator-repeats-parent.patch', '9a0d35671e46540bd2109602e3d27054d53e36c0d36d9671b0facb98d30eeb6a').
host_patch('swi-trie-gen-empty-hashed-root.patch', 'f2df58efc5fdfbb2139905a1df73c3e8d320b16e9b46a7e9101a708bf687f6e0').
host_patch('swi-ugraphs-implicit-append.patch', '91a8a47f2e696d302c106478b62cb37bac925a554bd5bedb7da135bab6498824').
host_patch('swi-unicode-map-empty-result-aborts.patch', '2e565b5c1cece3200d9310518b6c18aeeef52bee10b147ca47ff7f9146ec5883').
host_patch('swi-unicode-nfkc-casefold-keeps-ignorables.patch', 'b5ea23b0efc0ad9e6c4bfa8b76c079d17725179574aece2c293d1ef460e99edf').
host_patch('swi-unlinked-definition-uninitialised.patch', '3d56008f13a666ed917bcc5d78dbce4a923d90d4af7d60f24f5571d397935a49').
host_patch('swi-uuid-static-half-unlinked.patch', '18c6b3c8c869d1967e4f9b033d04f57b7f649eef84f37f48c74ca10e543e24d5').
host_patch('swi-wasm-js-bridge-assumes-window.patch', '84317f02835511f44f00a70772084427c3392372cd119997a97afddaf98d6450').
host_patch('swi-wasm-text-nul-truncation.patch', '1d5ea004a7f12f0ab9d78115b4702ec593b7f90cc68f42bffda0d1ca34852405').
host_patch('swi-wrapper-roundtrip-merges-closures.patch', '7da4db23ff7b999b5e6606299ec0df5b8b723e866c8db57943661a63b446815b').
