% Purpose: the host-workaround patches this engine refuses to boot without,
%   one host_patch(File, Sha256) fact per tests/checks/host_workarounds/*.patch.
% Generated by `sh tools/pymetta-host/declare-host.sh require`; the
%   host-declaration lane regenerates it and fails on any difference, so edit
%   the patches and rerun the command rather than this file.
:- module(metta_host_patches, [host_patch/2]).

host_patch('janus-callback-exception-leak.patch', '682b7866fc92ffb8f5a58cff80d258107efeea09ee048519e50fbcc53be36c83').
host_patch('swi-bound-clause-reference-ignores-snapshot.patch', 'db9913669e65b31ac4f2a7ff4f36ccfe4bb717dbb34b136c85de00215cb9a30b').
host_patch('swi-cached-undefined-supervisor.patch', 'c04bb1d905b11effb6d6022e94beba588f42bccbab8c56d04e78e17338a2ba24').
host_patch('swi-cleanup-window.patch', '36713ed4b86659d3f67337e845bbf86786a588229593ddbe9a892bfcc1d9db5f').
host_patch('swi-concurrent-import-removal-resets-provider.patch', '4ee42ff7c13cdedf01b90cc0355b8cf1af73b6266c6a2f249b900bb30301b492').
host_patch('swi-empty-indexed-snapshot.patch', '81c284a850e9d67a45f41da0b5f6772bb7ca1fbb389563a17a63a5fd28dbac12').
host_patch('swi-erased-definition-bypasses-loader.patch', '56bf3f614f408d1bf667e397b7f9d8e08162b38a10636e1eb3fa4baa61499fb2').
host_patch('swi-file-search-cache-autoload.patch', '9017274ed2cc99a2cc938f062881921c1faa8cea9d7d7b1e009242c754db7567').
host_patch('swi-file-search-cache-sweep.patch', 'cca21f0871baa9ccd749b1c10e9a8b6fdcc8c7910c2d6494ec1cb72a523165bd').
host_patch('swi-gc-in-frame-finished-listener-clears-a-live-slot.patch', '9895191655d5d5ea8776aea08811cda4ce6d6be26803994ea8f9aa05dabb30da').
host_patch('swi-locale-default-encoding.patch', 'f4a78676056b8fcafa64ab6b4988bddc0f1700afe90b210e94f7676b565d730c').
host_patch('swi-nested-retract-loses-outer-assert.patch', 'e07802e6a24d839288fb9805424cf583600066f129bfa15e644667902e281550').
host_patch('swi-qlf-extension-spec.patch', 'd5d4c1e2ab9df25977d53bcc497bdd286d946c41fd3d4f69285b8ec48a8dbbe6').
host_patch('swi-qlf-failed-include-source-module.patch', '00915b2e768e7eee601cc5d0acbcddd96aa1847addd591c33ec55f29f8ad0d14').
host_patch('swi-query-frame-discarded-on-engine-destroy.patch', '068f6ab5bcf8703df9292222e16663c6fc7b0df61cb52e0bcaed2926fbf9cccf').
host_patch('swi-thread-join-detach-window.patch', '418987e80776f6e69611af7912133f2398f208b3cbab5abd6209d1d4a576c192').
host_patch('swi-transaction-enumerator-repeats-parent.patch', '9a0d35671e46540bd2109602e3d27054d53e36c0d36d9671b0facb98d30eeb6a').
host_patch('swi-ugraphs-implicit-append.patch', '91a8a47f2e696d302c106478b62cb37bac925a554bd5bedb7da135bab6498824').
host_patch('swi-wrapper-roundtrip-merges-closures.patch', '7da4db23ff7b999b5e6606299ec0df5b8b723e866c8db57943661a63b446815b').
