"""Purpose: hold each patched-host requirement to the patches this tree carries, and the gate's own host to every requirement.

A patch sits in tests/checks/host_workarounds at the path of the swipl-devel
tree it patches (tools/pymetta-host/patch-root.sh), and each tree's patches are
one requirement: the patches to swipl-devel itself are the engine's, in
engine/host_patches.pl, which the engine refuses to boot without
(engine/host_check.pl); the patches to packages/swipy are janus's, in the
Python bridge's own metta/_binding/host_patches.pl, since no other host loads
janus. Three things can drift from that and this lane catches each:

  - every requirement file is GENERATED by
    `sh tools/pymetta-host/declare-host.sh require [TREE]`. A patch added or
    edited without regenerating leaves a requirement naming a set the build no
    longer produces, so this regenerates each and reports any difference;
  - a tree holding patches with no requirement file mapped below would be
    required by nobody, so it is reported rather than silently dropped;
  - the host this gate runs on must pass every requirement, checked through
    the engine's own metta_require_host_patches/2, so a lane run on an
    undeclared or stale host fails HERE, once and by name, rather than as
    every engine lane failing at its first boot.

Assumes:
  - sh and sha256sum, which declare-host.sh needs, and the interpreter chosen
    the way check_host_workarounds.py chooses it: SWIPL, else swipl on PATH
Guarantees:
  - a generated file that differs from the regenerated text is reported with
    the command that regenerates it, a tree holding patches that no
    requirement file covers is reported by name, and a host the check refuses
    is reported with the engine's own refusal text [tested:
    tests/checks/check_host_declaration_selftest.py; commit=WORKTREE]
Fails when:
  - read as a test of the patches themselves. Whether each patch removes its
    defect is the host-workarounds lane's question; this one asks only that
    the requirement, the declaration and the patches name the same set.
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DECLARE = Path("tools/pymetta-host/declare-host.sh")
PATCHES = Path("tests/checks/host_workarounds")
#: The requirement file each patched tree generates into. The key is the
#: tree's path inside swipl-devel, which is where its patches sit under
#: PATCHES; the empty key is swipl-devel itself.
GENERATED = {
    "": Path("engine/host_patches.pl"),
    "packages/swipy": Path("extensions/python/metta/_binding/host_patches.pl"),
}
#: Every process this starts goes through the repository's one bound, so a
#: hung swipl dies with the lane rather than outliving it.
BOUNDED = Path("tools/bounded.sh")


def interpreter() -> str:
    """The swipl the gate runs on, chosen as the host-workarounds lane chooses it."""
    return os.environ.get("SWIPL") or shutil.which("swipl") or "swipl"


def patched_trees(root: Path) -> list[str]:
    """Every tree some patch sits under, as its path inside swipl-devel."""
    trees = {patch.parent.relative_to(root / PATCHES).as_posix()
             for patch in (root / PATCHES).rglob("*.patch")}
    return sorted("" if tree == "." else tree for tree in trees)


def unrequired_trees(root: Path) -> list[str]:
    """A finding for each patched tree no requirement file covers."""
    return [f"the patches under {PATCHES / tree} are required by nobody: map the tree "
            f"to its requirement file in {Path(__file__).name}'s GENERATED"
            for tree in patched_trees(root) if tree not in GENERATED]


def stale_requirements(root: Path) -> list[str]:
    """Why each generated requirement differs from its patches, one finding per file."""
    findings = []
    for tree in patched_trees(root):
        if tree not in GENERATED:
            continue
        target = GENERATED[tree]
        command = ["sh", str(root / DECLARE), "require", *([tree] if tree else [])]
        ran = subprocess.run(["sh", str(ROOT / BOUNDED), *command],
                             capture_output=True, text=True, check=False)
        if ran.returncode != 0:
            findings.append(f"{DECLARE} require {tree} exited {ran.returncode}: {ran.stderr.strip()}")
            continue
        written = (root / target).read_text(encoding="utf-8") if (root / target).is_file() else ""
        if written != ran.stdout:
            findings.append(
                f"{target} does not match the patches in {PATCHES / tree}; regenerate it with "
                f"`sh {DECLARE} require{' ' + tree if tree else ''} > {target}`"
            )
    return findings


def refused_host(root: Path) -> list[str]:
    """The check's refusal of the gate's host, one finding per requirement it fails."""
    findings = []
    for tree in patched_trees(root):
        target = GENERATED.get(tree)
        if target is None or not (root / target).is_file():
            continue
        goal = (f"use_module('engine/host_check'), use_module('{target}'), "
                f"absolute_file_name('{target}', File, [access(read)]), "
                f"module_property(Module, file(File)), "
                f"findall(Name-Sha, Module:host_patch(Name, Sha), Required), "
                f"metta_host_check:metta_require_host_patches('{target}', Required)")
        ran = subprocess.run(
            ["sh", str(ROOT / BOUNDED), interpreter(), "-q", "-g", goal, "-t", "halt"],
            cwd=root, stdin=subprocess.DEVNULL, capture_output=True, text=True, check=False,
        )
        if ran.returncode != 0:
            findings.append(f"{interpreter()} is refused by the host check against "
                            f"{target}:\n{ran.stderr.strip()}")
    return findings


def check_tree(root: Path) -> list[str]:
    """Every way a requirement or the gate's host disagrees with the patches."""
    return unrequired_trees(root) + stale_requirements(root) + refused_host(root)


def main() -> int:
    """Check this tree and its host; print every finding; exit 1 when there is one."""
    findings = check_tree(ROOT)
    for finding in findings:
        print(finding)
    if findings:
        return 1
    counts = ", ".join(
        f"{GENERATED[tree]} {(ROOT / GENERATED[tree]).read_text(encoding='utf-8').count(chr(10) + 'host_patch(')}"
        for tree in patched_trees(ROOT))
    print(f"host declaration: each requirement matches its patches ({counts}) "
          f"and {interpreter()} declares them all")
    return 0


if __name__ == "__main__":
    sys.exit(main())
