"""Purpose: plant graph, ownership, path and shell drift in artifact fixtures.

Owns resources: each test creates a temporary directory under ai-tmp and removes
it with unittest cleanup after success or failure.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from dataclasses import replace
from itertools import product
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "extensions/python/tools"))

import artifacts as model  # noqa: E402


class ManifestTests(unittest.TestCase):
    """Exercise rendered shell as well as structural and projection checks."""

    def setUp(self) -> None:
        """Create two producers with a dependency opposing their lexical order."""
        scratch = tempfile.TemporaryDirectory(prefix="ai-artifact-manifest-", dir=ROOT / "ai-tmp")
        self.addCleanup(scratch.cleanup)
        self.root = Path(scratch.name)
        for name in ("input.txt", "emitter.py", "seed.txt", "use.txt"):
            (self.root / name).write_text("fixture\n", encoding="utf-8")
        command = ("@python", "@root/emitter.py")
        seed = model.Artifact("z-seed", ("input.txt",), command, (model.Output("seed.txt"),), command, (command,))
        self.rows = (replace(seed, name="a-use", outputs=(model.Output("use.txt"),), depends=("z-seed",)), seed)
        # Planted at the path the module under test names, not at a second
        # spelling of it. This fixture wrote `<root>/check.sh` while
        # `projections()` opened `<root>/tools/check.sh`, so every test here
        # died in setUp with FileNotFoundError once the drivers moved.
        for output in model.SHELL_OUTPUTS:
            driver = self.root / output.path
            driver.parent.mkdir(parents=True, exist_ok=True)
            text = driver.read_text(encoding="utf-8") if driver.exists() else "authored before\n"
            begin, end = output.region
            driver.write_text(text + f"{begin}\n{end}\nauthored after\n", encoding="utf-8")
        (self.root / model.GUIDE_MD).write_text(
            f"guide before\n{model.DOC_BEGIN}\n{model.DOC_END}\nguide after\n", encoding="utf-8",
        )
        self.render()

    def test_owner_and_notice_read_the_declared_outputs(self) -> None:
        """A generated path names its one owner and its notice; none or two owners refuse."""
        self.assertEqual(model.owner("seed.txt", self.rows, root=self.root).name, "z-seed")
        self.assertEqual(
            model.notice("seed.txt", self.rows, root=self.root),
            "GENERATED by emitter.py from input.txt: the z-seed artifact in "
            "extensions/python/tools/artifacts.py, whose z-seed lane refuses drift.",
        )
        with self.assertRaises(KeyError):
            model.owner("nobody.txt", self.rows, root=self.root)
        twice = (*self.rows, replace(self.rows[1], name="b-seed"))
        with self.assertRaises(KeyError):
            model.owner("seed.txt", twice, root=self.root)

    def render(self) -> None:
        """Install the fixture's current declared projections."""
        for path, text in model.projections(self.root, self.rows).items():
            path.write_text(text, encoding="utf-8")

    def test_planned_content_selects_header_owned_outputs(self) -> None:
        """A new or migrating file selects one producer before its marker exists."""
        first = replace(self.rows[0], outputs=(model.Output("new.txt", contains="first"),))
        second = replace(self.rows[1], outputs=(model.Output("new.txt", contains="second"),))
        rows = (first, second)
        for present in (False, True):
            if present:
                (self.root / "new.txt").write_text("authored prefix", encoding="utf-8")
            self.assertEqual(model.owner("new.txt", rows, self.root, content="second").name, second.name)
            self.assertIn(second.name, model.notice("new.txt", rows, self.root, content="second"))
            with self.assertRaises(KeyError):
                model.owner("new.txt", rows, self.root, content="neither")
            with self.assertRaises(KeyError):
                model.owner("new.txt", rows, self.root, content="first second")

    def problems(self, rows=None) -> str:
        """Collect the actual checker's diagnostics for the selected declarations."""
        return "\n".join(model.findings(self.root, self.rows if rows is None else rows))

    def test_topology_is_independent_of_insertion_order(self) -> None:
        """The alphabetically first consumer must wait for its producer."""
        self.assertEqual([row.name for row in model.ordered(self.rows)], ["z-seed", "a-use"])
        self.assertEqual(model.ordered(self.rows), model.ordered(tuple(reversed(self.rows))))
        self.assertEqual(self.problems(), "")

    def test_missing_output(self) -> None:
        """A deleted generated file names its owning artifact."""
        (self.root / "use.txt").unlink()
        self.assertIn("a-use: missing output: use.txt", self.problems())

    def test_missing_input_and_command(self) -> None:
        """Both source absence and a removed executable remain visible."""
        (self.root / "input.txt").unlink()
        (self.root / "emitter.py").unlink()
        self.assertIn("missing input: input.txt", self.problems())
        self.assertIn("missing command path: @root/emitter.py", self.problems())

    def test_cycle_and_unknown_dependency(self) -> None:
        """Neither an impossible order nor an unresolved predecessor is accepted."""
        use, seed = self.rows
        self.assertIn("artifact dependency cycle:", self.problems((use, replace(seed, depends=("a-use",)))))
        self.assertIn("unknown artifact dependencies: absent", self.problems((replace(use, depends=("absent",)), seed)))

    def test_duplicate_identity_and_overlapping_output(self) -> None:
        """Artifact names and generated bytes cannot have competing owners."""
        use, seed = self.rows
        self.assertIn("duplicate artifact name", self.problems((seed, seed)))
        self.assertIn("overlapping artifact output: seed.txt", self.problems((replace(use, outputs=seed.outputs), seed)))

    def test_inverted_executable_order_is_drift(self) -> None:
        """A valid selection cannot hide reversed literal gate declarations."""
        path = self.root / model.CHECK_SH
        text = path.read_text(encoding="utf-8")
        text = text.replace("run GATE z-seed ", "run GATE ai-swap ")
        text = text.replace("run GATE a-use ", "run GATE z-seed ").replace("run GATE ai-swap ", "run GATE a-use ")
        path.write_text(text, encoding="utf-8")
        self.assertIn(f"projection drift: {model.CHECK_SH}", self.problems())

    def test_manifest_can_describe_its_own_region(self) -> None:
        """Printed region names cannot become extra regeneration delimiters."""
        use, seed = self.rows
        self.rows = (replace(use, outputs=(model.Output(model.GUIDE_MD, (model.DOC_BEGIN, model.DOC_END)),)), seed)
        self.render()
        self.assertEqual(self.problems(), "")
        self.render()
        self.assertEqual(self.problems(), "")
        self.assertIn("&lt;!-- begin generated artifact manifest --&gt;", (self.root / model.GUIDE_MD).read_text(encoding="utf-8"))

    def test_each_projection_detects_an_independent_edit(self) -> None:
        """Selection, execution and documentation each carry their own witness."""
        for relative, old in ((model.CHECK_SH, "GENERATED_ARTIFACT_LANES="), (model.CHECK_SH, "run GATE a-use "),
                              (model.GUIDE_MD, "| `a-use` |")):
            with self.subTest(relative=relative, old=old):
                self.render()
                path = self.root / relative
                path.write_text(path.read_text(encoding="utf-8").replace(old, "mutated", 1), encoding="utf-8")
                self.assertIn(f"projection drift: {relative}", self.problems())

    def test_new_row_reaches_both_projections(self) -> None:
        """Adding one declaration requires no second artifact roster."""
        new = replace(self.rows[0], name="new-output", outputs=(model.Output("new.txt"),), depends=("a-use",))
        (self.root / "new.txt").write_text("fixture", encoding="utf-8")
        self.rows += (new,)
        self.assertIn(f"projection drift: {model.CHECK_SH}", self.problems())
        self.assertIn("projection drift: DEVELOPING.md", self.problems())
        self.render()
        self.assertEqual(self.problems(), "")
        self.assertIn("run GATE new-output ", (self.root / model.CHECK_SH).read_text(encoding="utf-8"))
        self.assertIn("| `new-output` |", (self.root / model.GUIDE_MD).read_text(encoding="utf-8"))

    def test_regions_allow_disjoint_ownership_and_preserve_prose(self) -> None:
        """Regions may share a file while keeping separate ownership intervals."""
        path = self.root / "seed.txt"
        path.write_text("before\n<one>first</one>\nbetween\n<two>second</two>\nafter", encoding="utf-8")
        use, seed = self.rows
        seed = replace(seed, outputs=(model.Output("seed.txt", ("<one>", "</one>")),))
        use = replace(use, outputs=(model.Output("seed.txt", ("<two>", "</two>")),))
        self.rows = (use, seed)
        self.render()
        self.assertEqual(self.problems(), "")
        self.assertIn("overlapping artifact output", self.problems((replace(use, outputs=seed.outputs), seed)))
        changed = model.region(path.read_text(encoding="utf-8"), "<one>", "</one>", "replacement")
        self.assertEqual(changed, "before\n<one>\nreplacement\n</one>\nbetween\n<two>second</two>\nafter")
        for text in ("<one></one><one>", "</one><one>"):
            with self.assertRaisesRegex(ValueError, "one ordered generated region"):
                model.region(text, "<one>", "</one>", "replacement")

    def test_shell_expands_groups_and_individual_artifacts(self) -> None:
        """A real POSIX shell selects the declared checks and mutation witnesses."""
        rows = model.ordered(self.rows)
        script = model.selection(rows) + '\nprintf "%s\\n" "$WANT"\n'
        cases = {
            "generated-artifacts": {"generated-artifacts", "z-seed", "a-use", "z-seed-selftest", "a-use-selftest"},
            "generated-artifacts-selftest": {"generated-artifacts-selftest", "z-seed-selftest", "a-use-selftest"},
            "a-use": {"a-use", "a-use-selftest"},
        }
        for selection, expected in cases.items():
            with self.subTest(selection=selection):
                result = subprocess.run(["sh", "-c", script, "fixture", selection], capture_output=True, text=True, check=True)
                self.assertEqual(set(result.stdout.split()), expected)
        subprocess.run(["sh", "-n"], input=model.lanes(rows), text=True, check=True)

    def test_subject_partition_moves_checks_and_witnesses_without_stale_registrations(self) -> None:
        """Every input/output combination routes once and regeneration clears the old owner."""
        seat_gate = "extensions/python/check.sh"
        seat = "extensions/python/"
        for input_prefix, output_prefix in product(("", seat), repeat=2):
            with self.subTest(input=input_prefix, output=output_prefix):
                for name in (input_prefix + "input.txt", output_prefix + "use.txt"):
                    path = self.root / name
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_text("fixture\n", encoding="utf-8")
                self.rows = (replace(self.rows[0], inputs=(input_prefix + "input.txt",),
                                     outputs=(model.Output(output_prefix + "use.txt"),)), self.rows[1])
                expected = seat_gate if input_prefix == output_prefix == seat else model.CHECK_SH
                self.assertEqual(model.gate(self.rows[0]), expected)
                self.render()
                rendered = model.projections(self.root, self.rows)
                self.render()
                self.assertEqual(model.projections(self.root, self.rows), rendered)
                self.assertEqual(self.problems(), "")
                for relative in (model.CHECK_SH, seat_gate):
                    text = (self.root / relative).read_text(encoding="utf-8")
                    for name in ("a-use", "a-use-selftest"):
                        self.assertEqual(text.count(f"run GATE {name} "), int(relative == expected))
                path = self.root / expected
                original = path.read_text(encoding="utf-8")
                path.write_text(original.replace("run GATE a-use ", "run GATE missing "), encoding="utf-8")
                self.assertIn(f"projection drift: {expected}", self.problems())
                self.render()
        # Moving the last component row back must empty its old region too.
        self.rows = (replace(self.rows[0], inputs=("input.txt",)), self.rows[1])
        self.render()
        self.assertNotIn("run GATE a-use ", (self.root / seat_gate).read_text(encoding="utf-8"))

    def test_real_runner_selects_generated_groups_through_each_owner(self) -> None:
        """The actual sourced runner lists each owned check and witness exactly once."""
        for owner in (None, "extensions/python"):
            driver = ROOT / (model.CHECK_SH if owner is None else owner + "/check.sh")
            rows = [row for row in model.ARTIFACTS if owner is None or model.gate(row) == owner + "/check.sh"]
            for selection in ("generated-artifacts", "generated-artifacts-selftest", "protocol-sync", "init-stub"):
                with self.subTest(owner=owner, selection=selection):
                    selected = rows if selection.startswith("generated-artifacts") else [row for row in rows if row.name == selection]
                    expected = [f"GATE {row.name}{suffix}" for row in selected
                                for suffix in (("-selftest",) if selection.endswith("-selftest") else ("", "-selftest"))]
                    result = subprocess.run(["sh", str(driver), "--list", selection], cwd=ROOT,
                                            capture_output=True, text=True, check=True)
                    self.assertCountEqual(result.stdout.splitlines(), expected)

    def test_shell_argv_quoting_does_not_execute_metacharacters(self) -> None:
        """Only the interpreter and root slots expand in executable argv."""
        literal = 'spaces $METTA_ARTIFACT_TEST `uname` $(uname) "quote"'
        script = 'PY=python\nHERE=/fixture\n' + model.command_text(("printf", "%s\\n", literal, "@root/" + literal))
        result = subprocess.run(["sh", "-c", script], capture_output=True, text=True, check=True)
        self.assertEqual(result.stdout.splitlines(), [literal, "/fixture/" + literal])


if __name__ == "__main__":
    unittest.main()
