"""Purpose: plant graph, ownership, path and shell drift in artifact fixtures.

Owns resources: each test creates a temporary directory under ai-tmp and removes
it with unittest cleanup after success or failure.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from dataclasses import replace
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "extensions/python/tools"))

import artifacts as model  # noqa: E402


class ManifestTests(unittest.TestCase):
    """Exercise rendered shell as well as structural and projection checks."""

    def setUp(self) -> None:
        """Create two producers with a dependency opposing their lexical order."""
        scratch = tempfile.TemporaryDirectory(prefix="ai-artifact-manifest-", dir=ROOT / "ai-tmp")
        self.addCleanup(scratch.cleanup)
        self.root = Path(scratch.name)
        for name in ("input.txt", "emitter.py", "seed.txt", "use.txt"):
            (self.root / name).write_text("fixture\n", encoding="utf-8")
        command = ("@python", "@root/emitter.py")
        seed = model.Artifact("z-seed", ("input.txt",), command, (model.Output("seed.txt"),), command, (command,))
        self.rows = (replace(seed, name="a-use", outputs=(model.Output("use.txt"),), depends=("z-seed",)), seed)
        (self.root / "check.sh").write_text(
            f"authored before\n{model.BEGIN}\n{model.END}\n"
            f"{model.LANES_BEGIN}\n{model.LANES_END}\nauthored after\n", encoding="utf-8",
        )
        (self.root / "DEVELOPING.md").write_text(
            f"guide before\n{model.DOC_BEGIN}\n{model.DOC_END}\nguide after\n", encoding="utf-8",
        )
        self.render()

    def test_owner_and_notice_read_the_declared_outputs(self) -> None:
        """A generated path names its one owner and its notice; none or two owners refuse."""
        self.assertEqual(model.owner("seed.txt", self.rows, root=self.root).name, "z-seed")
        self.assertEqual(
            model.notice("seed.txt", self.rows, root=self.root),
            "GENERATED by emitter.py from input.txt: the z-seed artifact in "
            "extensions/python/tools/artifacts.py, whose z-seed lane refuses drift.",
        )
        with self.assertRaises(KeyError):
            model.owner("nobody.txt", self.rows, root=self.root)
        twice = (*self.rows, replace(self.rows[1], name="b-seed"))
        with self.assertRaises(KeyError):
            model.owner("seed.txt", twice, root=self.root)

    def render(self) -> None:
        """Install the fixture's current declared projections."""
        for path, text in model.projections(self.root, self.rows).items():
            path.write_text(text, encoding="utf-8")

    def problems(self, rows=None) -> str:
        """Collect the actual checker's diagnostics for the selected declarations."""
        return "\n".join(model.findings(self.root, self.rows if rows is None else rows))

    def test_topology_is_independent_of_insertion_order(self) -> None:
        """The alphabetically first consumer must wait for its producer."""
        self.assertEqual([row.name for row in model.ordered(self.rows)], ["z-seed", "a-use"])
        self.assertEqual(model.ordered(self.rows), model.ordered(tuple(reversed(self.rows))))
        self.assertEqual(self.problems(), "")

    def test_missing_output(self) -> None:
        """A deleted generated file names its owning artifact."""
        (self.root / "use.txt").unlink()
        self.assertIn("a-use: missing output: use.txt", self.problems())

    def test_missing_input_and_command(self) -> None:
        """Both source absence and a removed executable remain visible."""
        (self.root / "input.txt").unlink()
        (self.root / "emitter.py").unlink()
        self.assertIn("missing input: input.txt", self.problems())
        self.assertIn("missing command path: @root/emitter.py", self.problems())

    def test_cycle_and_unknown_dependency(self) -> None:
        """Neither an impossible order nor an unresolved predecessor is accepted."""
        use, seed = self.rows
        self.assertIn("artifact dependency cycle:", self.problems((use, replace(seed, depends=("a-use",)))))
        self.assertIn("unknown artifact dependencies: absent", self.problems((replace(use, depends=("absent",)), seed)))

    def test_duplicate_identity_and_overlapping_output(self) -> None:
        """Artifact names and generated bytes cannot have competing owners."""
        use, seed = self.rows
        self.assertIn("duplicate artifact name", self.problems((seed, seed)))
        self.assertIn("overlapping artifact output: seed.txt", self.problems((replace(use, outputs=seed.outputs), seed)))

    def test_inverted_executable_order_is_drift(self) -> None:
        """A valid selection cannot hide reversed literal gate declarations."""
        path = self.root / "check.sh"
        text = path.read_text(encoding="utf-8")
        text = text.replace("run GATE z-seed ", "run GATE ai-swap ")
        text = text.replace("run GATE a-use ", "run GATE z-seed ").replace("run GATE ai-swap ", "run GATE a-use ")
        path.write_text(text, encoding="utf-8")
        self.assertIn("projection drift: check.sh", self.problems())

    def test_manifest_can_describe_its_own_region(self) -> None:
        """Printed region names cannot become extra regeneration delimiters."""
        use, seed = self.rows
        self.rows = (replace(use, outputs=(model.Output("DEVELOPING.md", (model.DOC_BEGIN, model.DOC_END)),)), seed)
        self.render()
        self.assertEqual(self.problems(), "")
        self.render()
        self.assertEqual(self.problems(), "")
        self.assertIn("&lt;!-- begin generated artifact manifest --&gt;", (self.root / "DEVELOPING.md").read_text(encoding="utf-8"))

    def test_each_projection_detects_an_independent_edit(self) -> None:
        """Selection, execution and documentation each carry their own witness."""
        for relative, old in (("check.sh", "GENERATED_ARTIFACT_LANES="), ("check.sh", "run GATE a-use "),
                              ("DEVELOPING.md", "| `a-use` |")):
            with self.subTest(relative=relative, old=old):
                self.render()
                path = self.root / relative
                path.write_text(path.read_text(encoding="utf-8").replace(old, "mutated", 1), encoding="utf-8")
                self.assertIn(f"projection drift: {relative}", self.problems())

    def test_new_row_reaches_both_projections(self) -> None:
        """Adding one declaration requires no second artifact roster."""
        new = replace(self.rows[0], name="new-output", outputs=(model.Output("new.txt"),), depends=("a-use",))
        (self.root / "new.txt").write_text("fixture", encoding="utf-8")
        self.rows += (new,)
        self.assertIn("projection drift: check.sh", self.problems())
        self.assertIn("projection drift: DEVELOPING.md", self.problems())
        self.render()
        self.assertEqual(self.problems(), "")
        self.assertIn("run GATE new-output ", (self.root / "check.sh").read_text(encoding="utf-8"))
        self.assertIn("| `new-output` |", (self.root / "DEVELOPING.md").read_text(encoding="utf-8"))

    def test_regions_allow_disjoint_ownership_and_preserve_prose(self) -> None:
        """Regions may share a file while keeping separate ownership intervals."""
        path = self.root / "seed.txt"
        path.write_text("before\n<one>first</one>\nbetween\n<two>second</two>\nafter", encoding="utf-8")
        use, seed = self.rows
        seed = replace(seed, outputs=(model.Output("seed.txt", ("<one>", "</one>")),))
        use = replace(use, outputs=(model.Output("seed.txt", ("<two>", "</two>")),))
        self.rows = (use, seed)
        self.render()
        self.assertEqual(self.problems(), "")
        self.assertIn("overlapping artifact output", self.problems((replace(use, outputs=seed.outputs), seed)))
        changed = model.region(path.read_text(encoding="utf-8"), "<one>", "</one>", "replacement")
        self.assertEqual(changed, "before\n<one>\nreplacement\n</one>\nbetween\n<two>second</two>\nafter")
        for text in ("<one></one><one>", "</one><one>"):
            with self.assertRaisesRegex(ValueError, "one ordered generated region"):
                model.region(text, "<one>", "</one>", "replacement")

    def test_shell_expands_groups_and_individual_artifacts(self) -> None:
        """A real POSIX shell selects the declared checks and mutation witnesses."""
        rows = model.ordered(self.rows)
        script = model.selection(rows) + '\nprintf "%s\\n" "$WANT"\n'
        cases = {
            "generated-artifacts": {"generated-artifacts", "z-seed", "a-use", "z-seed-selftest", "a-use-selftest"},
            "generated-artifacts-selftest": {"generated-artifacts-selftest", "z-seed-selftest", "a-use-selftest"},
            "a-use": {"a-use", "a-use-selftest"},
        }
        for selection, expected in cases.items():
            with self.subTest(selection=selection):
                result = subprocess.run(["sh", "-c", script, "fixture", selection], capture_output=True, text=True, check=True)
                self.assertEqual(set(result.stdout.split()), expected)
        subprocess.run(["sh", "-n"], input=model.lanes(rows), text=True, check=True)

    def test_shell_argv_quoting_does_not_execute_metacharacters(self) -> None:
        """Only the interpreter and root slots expand in executable argv."""
        literal = 'spaces $METTA_ARTIFACT_TEST `uname` $(uname) "quote"'
        script = 'PY=python\nHERE=/fixture\n' + model.command_text(("printf", "%s\\n", literal, "@root/" + literal))
        result = subprocess.run(["sh", "-c", script], capture_output=True, text=True, check=True)
        self.assertEqual(result.stdout.splitlines(), [literal, "/fixture/" + literal])


if __name__ == "__main__":
    unittest.main()
