% Purpose: verify HTTP bytes, parsed fields and ownership over real loopback sockets.
% Guarantees: generated byte/method cases cross the transport; resource tests
% cover completion, cut, exceptions, cancellation, concurrent close and port reuse.
% [tested: lib_http; commit=WORKTREE].
% Owns resources: fixtures stop every server, close every File handle, join
% workers, release execution spaces and remove temporary predicate wrappers.

:- ensure_loaded('../../../../engine/qlf_boot.pl').
:- ensure_loaded('../../../../engine/metta.pl').
:- use_module('../../../../lib/lib_http/lib_http').
:- use_module('../../../../lib/lib_file/lib_file',
              [adopt_file_stream/2,'file-close!'/2,'file-read-bytes!'/2,'file-read-bytes!'/3]).
:- use_module(library(http/thread_httpd), [http_current_server/2,http_current_worker/2]).
:- use_module(library(socket), [tcp_socket/1,tcp_bind/2,tcp_close_socket/1]).
:- use_module(library(lists), [member/2,memberchk/2,numlist/3]).
:- use_module(library(thread), [concurrent/3]).
:- use_module(library(prolog_wrap), [wrap_predicate/4,unwrap_predicate/2]).
:- initialization(http_suite_setup).

http_suite_setup :-
    import_prolog_functions(['http-suite-return','http-suite-echo','http-suite-answers',
                            'http-suite-boom','http-suite-spin','http-suite-self-stop',
                            'http-suite-nested'],_).

'http-suite-return'(Response,_Request,Response).
'http-suite-echo'(['http-request',Method,_Path,Target,_Fields,Bytes],
                  ['http-response',201,[["X-Method",Text],["X-Target",Target]],Bytes]) :-
    atom_string(Method,Text).
'http-suite-answers'(Resource,[Resource,Answer]) :- member(Answer,[first,second]).
'http-suite-boom'(Resource,_) :- throw(error(http_scope(Resource),_)).
'http-suite-spin'(_,_) :- repeat,fail.
'http-suite-self-stop'(_,['http-response',409,[],[]]) :-
    thread_self(Self),http_current_worker(Port,Self),
    http_current_server(lib_http:serve(ID,_,_),Port),
    catch('http-server-stop!'(['http-server',"127.0.0.1",Port,ID],_),Error,true),
    Error=error(permission_error(stop,current_http_server,_),_).
'http-suite-nested'(Main,_,['http-response',200,[],[42]]) :-
    thread_self(Self),thread_send_message(Main,http_nested_ready(Self)),
    thread_get_message(http_nested_go),
    setup_call_cleanup('http-server-start!'("127.0.0.1",0,'http-suite-echo',[[workers,1]],Child),
        ('http-server-url'(Child,URL),'http-request!'(get,URL,[],['http-response',201,_,[]])),
        'http-server-stop!'(Child,_)).

:- begin_tests(lib_http).
:- meta_predicate must_throw(0, ?), with_server(+, 2).

must_throw(Goal,Expected) :-
    catch(Goal,Error,true),assertion(nonvar(Error)),assertion(Error=Expected).

with_server(Handler,Goal) :-
    setup_call_cleanup('http-server-start!'("127.0.0.1",0,Handler,[[workers,2]],Server),
        ('http-server-url'(Server,URL),call(Goal,Server,URL)),
        'http-server-stop!'(Server,_)).

fixed(Response,['http-suite-return',[quote,Response]]).
handles(Handles) :- findall(H-S,lib_file:metta_file(H,S),Handles).
closed(['http-response',_,_,Handle]) :- assertion(\+ lib_file:metta_file(Handle,_)).
stopped(['http-server',_,Port,ID]) :-
    assertion(\+ http_current_server(lib_http:serve(ID,_,_),Port)).
available_port(Port) :-
    setup_call_cleanup(tcp_socket(Socket),tcp_bind(Socket,'127.0.0.1':Port),
                       tcp_close_socket(Socket)).

test(http_capabilities_are_separate) :-
    metta_engine:metta_platform_capability(http,HTTP,_),
    metta_engine:metta_platform_capability(https,HTTPS,_),
    assertion(memberchk(library(http/http_open),HTTP)),
    assertion(memberchk(library(http/http_ssl_plugin),HTTPS)),
    assertion(memberchk(library(ssl),HTTPS)),assertion(\+ memberchk(library(ssl),HTTP)).

test(methods_and_generated_binary_payloads) :- with_server('http-suite-echo',echo_cases).
echo_cases(_,URL) :-
    'http-methods'(Methods),
    forall((member(Method,Methods),member(Length,[0,1,255,256,4097])),
        (findall(Byte,(between(1,Length,I),Byte is (I*73) mod 256),Bytes),
         'http-request!'(Method,URL,[[body,"application/octet-stream",Bytes]],
                         ['http-response',Code,Fields,Actual]),
         assertion(Code==201),atom_string(Method,Text),
         once('http-header'(Fields,"x-method",Reported)),assertion(Reported==Text),
         (Method==head -> assertion(Actual==[]) ; assertion(Actual==Bytes)))),
    numlist(0,255,EveryByte),
    'http-request!'(post,URL,[[body,"application/octet-stream",EveryByte]],
                    ['http-response',_,_,Returned]),assertion(Returned==EveryByte).

test(https_uses_tls_and_refuses_a_plaintext_listener,
     [condition(exists_source(library(http/http_ssl_plugin)))]) :-
    with_server('http-suite-echo',tls_case).
tls_case(_,URL) :-
    sub_string(URL,4,_,0,Rest),string_concat("https",Rest,Secure),
    must_throw('http-request!'(get,Secure,[[timeout,5]],_),error(_,_)),
    'http-request!'(get,URL,[],Response),assertion(Response=['http-response',201,_,[]]).

test(repeated_headers_and_cookie_structure) :-
    fixed(['http-response',299,[["X-Reply","one"],["X-Reply","two"],
                               ["Set-Cookie","sid=value; Path=/; HttpOnly"]],[255]],Handler),
    with_server(Handler,header_case).
header_case(_,URL) :-
    'http-request!'(get,URL,[],['http-response',Code,Fields,Bytes]),
    assertion(Code==299),assertion(Bytes==[255]),
    findall(V,'http-header'(Fields,"X-REPLY",V),Values),assertion(Values==["one","two"]),
    findall(V,'http-header'(Fields,"missing",V),Missing),assertion(Missing==[]),
    once('http-header'(Fields,"set-cookie",Cookie)),
    assertion(Cookie==["set_cookie","sid","value",[["=","path","/"],["=","httponly","true"]]]).

test(no_body_statuses_close_their_parent_stream) :-
    handles(Before),
    forall(member(Status,[204,205,304]),
        (fixed(['http-response',Status,[],[]],Handler),
         with_server(Handler,no_body_case(Status)))),
    handles(After),assertion(After==Before).
no_body_case(Status,_,URL) :-
    'http-request!'(get,URL,[],Response),assertion(Response=['http-response',Status,_,[]]),
    once('with-http'(head,URL,[],'http-suite-answers',[Stream,_])),closed(Stream).

test(status_and_redirect_policy) :-
    fixed(['http-response',418,[],[1,2]],Target),
    with_server(Target,redirect_target).
redirect_target(_,TargetURL) :-
    fixed(['http-response',307,[["Location",TargetURL]],[]],Redirect),
    with_server(Redirect,redirect_case).
redirect_case(_,URL) :-
    'http-request!'(get,URL,[],['http-response',Status,_,Bytes]),
    assertion(Status==307),assertion(Bytes==[]),
    'http-request!'(get,URL,[[redirect,true]],Followed),
    assertion(Followed=['http-response',418,_,[1,2]]),
    must_throw('http-request!'(get,URL,[[redirect,true],['max-redirect',0]],_),error(_,_)).

test(stream_cursor_and_idempotent_close) :-
    fixed(['http-response',200,[],[0,128,255]],Handler),with_server(Handler,stream_case).
stream_case(_,URL) :-
    setup_call_cleanup('http-open!'(get,URL,[],['http-response',_,_,Handle]),
        ('file-read-bytes!'(Handle,2,Prefix),assertion(Prefix==[0,128]),
         'file-read-bytes!'(Handle,Rest),assertion(Rest==[255]),
         'file-read-bytes!'(Handle,Empty),assertion(Empty==[])),
        'file-close!'(Handle,_)),
    'file-close!'(Handle,Done),assertion(Done==true),
    must_throw('file-read-bytes!'(Handle,_),error(existence_error(metta_file_handle,Handle),_)).

test(response_scopes_release_on_every_exit) :-
    fixed(['http-response',200,[],[42]],Handler),with_server(Handler,response_scopes).
response_scopes(_,URL) :-
    handles(Before),
    findall(Answer,'with-http'(get,URL,[],'http-suite-answers',Answer),Answers),
    Answers=[[Resource,first],[Resource,second]],closed(Resource),
    once('with-http'(get,URL,[],'http-suite-answers',[Cut,_])),closed(Cut),
    catch('with-http'(get,URL,[],'http-suite-boom',_),error(http_scope(Thrown),_),true),closed(Thrown),
    call_with_inference_limit('with-http'(get,URL,[],'http-suite-spin',_),200000,Limit),
    assertion(Limit==inference_limit_exceeded),handles(After),assertion(After==Before).

test(server_scopes_release_on_every_exit) :-
    fixed(['http-response',200,[],[]],Handler),
    findall(Answer,'with-http-server'("127.0.0.1",0,Handler,[[workers,1]],
                                     'http-suite-answers',Answer),Answers),
    Answers=[[Server,first],[Server,second]],stopped(Server),
    once('with-http-server'("127.0.0.1",0,Handler,[[workers,1]],'http-suite-answers',[Cut,_])),
    stopped(Cut),
    catch('with-http-server'("127.0.0.1",0,Handler,[[workers,1]],'http-suite-boom',_),
          error(http_scope(Thrown),_),true),stopped(Thrown),
    findall(Port,http_current_server(lib_http:serve(_,_,_),Port),Before),
    call_with_inference_limit('with-http-server'("127.0.0.1",0,Handler,[[workers,1]],
                                                'http-suite-spin',_),200000,Limit),
    assertion(Limit==inference_limit_exceeded),
    findall(Port,http_current_server(lib_http:serve(_,_,_),Port),After),assertion(After==Before).

test(server_identity_survives_port_reuse) :-
    fixed(['http-response',200,[],[]],Handler),
    'http-server-start!'("127.0.0.1",0,Handler,[[workers,1]],Old),
    Old=['http-server',_,Port,_],'http-server-stop!'(Old,_),
    setup_call_cleanup('http-server-start!'("127.0.0.1",Port,Handler,[[workers,1]],New),
        (assertion(New\==Old),'http-server-stop!'(Old,_),stopped(Old),
         'http-server-url'(New,URL),'http-request!'(get,URL,[],Reply),
         assertion(Reply=['http-response',200,_,[]])),
        'http-server-stop!'(New,_)).

test(concurrent_stops_and_stale_acknowledgements) :-
    fixed(['http-response',200,[],[]],Handler),
    thread_self(Self),thread_send_message(Self,http_stopped),
    with_server(Handler,concurrent_stops),
    assertion(thread_get_message(Self,http_stopped,[timeout(0)])),
    assertion(\+ thread_peek_message(http_stopped)).
concurrent_stops(Server,_) :-
    concurrent(2,[lib_http:'http-server-stop!'(Server,A),lib_http:'http-server-stop!'(Server,B)],[]),
    assertion(A==true),assertion(B==true),stopped(Server).

test(worker_cannot_stop_its_own_server) :- with_server('http-suite-self-stop',self_stop_case).
self_stop_case(_,URL) :-
    'http-request!'(get,URL,[],Reply),assertion(Reply=['http-response',409,_,[]]).

test(a_stopping_server_worker_can_start_another_server) :-
    thread_self(Main),with_server(['http-suite-nested',[quote,Main]],nested_case(Main)).
nested_case(Main,Server,URL) :-
    Server=['http-server',_,Port,_],
    setup_call_cleanup(
        wrap_predicate(lib_http:stop_native_server(Stopping),http_stop_notice,Wrapped,
                       ((Stopping==Port -> thread_send_message(Main,http_stopping(Port)) ; true),call(Wrapped))),
        (thread_create(('http-request!'(get,URL,[],Reply),thread_send_message(Main,http_nested_reply(Reply))),Requester,[]),
         thread_get_message(http_nested_ready(Worker)),
         thread_create('http-server-stop!'(Server,_),Stopper,[]),
         thread_get_message(http_stopping(Port)),thread_send_message(Worker,http_nested_go),
         thread_join(Requester,RequestStatus),thread_join(Stopper,StopStatus),
         assertion(RequestStatus==true),assertion(StopStatus==true),
         thread_get_message(http_nested_reply(Response)),assertion(Response=['http-response',200,_,[42]])),
        unwrap_predicate(lib_http:stop_native_server(_),http_stop_notice)).

test(two_servers_capture_different_execution_modules) :-
    setup_call_cleanup('new-space'(Left),
        setup_call_cleanup('new-space'(Right),module_case(Left,Right),spaces:metta_release_space(Right)),
        spaces:metta_release_space(Left)).
module_case(Left,Right) :-
    filereader:metta_host_run_source("(: same-http-route (-> Expression Expression))\n(= (same-http-route $r) (http-response 201 () (1)))",Left,[],_),
    filereader:metta_host_run_source("(: same-http-route (-> Expression Expression))\n(= (same-http-route $r) (http-response 202 () (2)))",Right,[],_),
    spaces:space_module(Left,LM),spaces:space_module(Right,RM),
    setup_call_cleanup(with_metta_module(LM,'http-server-start!'("127.0.0.1",0,'same-http-route',[[workers,1]],LS)),
        setup_call_cleanup(with_metta_module(RM,'http-server-start!'("127.0.0.1",0,'same-http-route',[[workers,1]],RS)),
            ('http-server-url'(LS,LU),'http-server-url'(RS,RU),
             'http-request!'(get,LU,[],LA),'http-request!'(get,RU,[],RA),
             assertion(LA=['http-response',201,_,[1]]),assertion(RA=['http-response',202,_,[2]])),
            'http-server-stop!'(RS,_)),
        'http-server-stop!'(LS,_)).

test(adoption_failure_releases_stream) :-
    handles(Before),open_string("owned",Stream),
    must_throw(adopt_file_stream(Stream,7),error(_,_)),
    assertion(\+ is_stream(Stream)),handles(After),assertion(After==Before).

test(adoption_cancellation_withdraws_the_registered_handle) :-
    handles(Before),open_string("owned",Stream),
    setup_call_cleanup(
        wrap_predicate(system:assertz(Clause),http_adopt_abort,Wrapped,
                       (call(Wrapped),(Clause=lib_file:metta_file(_,Stream) -> throw(adoption_cancelled) ; true))),
        must_throw(adopt_file_stream(Stream,_),adoption_cancelled),
        unwrap_predicate(system:assertz(_),http_adopt_abort)),
    assertion(\+ is_stream(Stream)),handles(After),assertion(After==Before).

close_barrier(Main) :-
    thread_self(Self),thread_send_message(Main,ready(Self)),thread_get_message(continue).
test(concurrent_file_close_claims_once) :-
    open_string("owned",Stream),adopt_file_stream(Stream,Handle),thread_self(Main),
    setup_call_cleanup(
        wrap_predicate(system:with_mutex(Mutex,_Goal),http_close_barrier,Wrapped,
                       ((Mutex=='$metta_files' -> close_barrier(Main) ; true),call(Wrapped))),
        (thread_create('file-close!'(Handle,_),A,[]),thread_create('file-close!'(Handle,_),B,[]),
         thread_get_message(ready(_)),thread_get_message(ready(_)),
         thread_send_message(A,continue),thread_send_message(B,continue),
         thread_join(A,SA),thread_join(B,SB),assertion(SA==true),assertion(SB==true)),
        unwrap_predicate(system:with_mutex(_,_),http_close_barrier)),
    assertion(\+ is_stream(Stream)),assertion(\+ lib_file:metta_file(Handle,_)).

test(startup_rollback_releases_workers_queue_and_port) :-
    available_port(Port),format(atom(Alias),'http@~d',[Port]),
    format(atom(Queue),'httpd@127.0.0.1:~d',[Port]),
    setup_call_cleanup(thread_create(thread_get_message(stop),Thread,[alias(Alias)]),
        must_throw('http-server-start!'("127.0.0.1",Port,'http-suite-echo',[[workers,1]],_),
                   error(permission_error(create,thread,Alias),_)),
        (thread_send_message(Thread,stop),thread_join(Thread,true))),
    assertion(\+ lib_http:queue_exists(Queue)),assertion(\+ thread_httpd:queue_worker(Queue,_)),
    setup_call_cleanup(tcp_socket(Socket),tcp_bind(Socket,'127.0.0.1':Port),tcp_close_socket(Socket)).

test(transaction_refusal_precedes_listener_acquisition) :-
    setup_call_cleanup(
        wrap_predicate(lib_http:listener(_,_,_,_,_),http_transaction_probe,_Wrapped,
                       throw(listener_was_entered)),
        must_throw(transaction('http-server-start!'("127.0.0.1",0,'http-suite-echo',[],_)),
                   error(permission_error(access,http_server_in_transaction,_),_)),
        unwrap_predicate(lib_http:listener(_,_,_,_,_),http_transaction_probe)),
    must_throw(transaction('http-server-stop!'(['http-server',"127.0.0.1",1,0],_)),
               error(permission_error(access,http_server_in_transaction,_),_)).

test(client_refusals_precede_io) :-
    URL="http://127.0.0.1:1/",
    forall(member(Goal,['http-request!'(invented,URL,[],_),
                        'http-request!'(get,"file:///etc/passwd",[],_),
                        'http-request!'(get,"http://x/ bad",[],_),
                        'http-request!'(get,"http:///",[],_)]),must_throw(Goal,error(_,_))),
    forall(member(Option,[[header,"bad:name","x"],[header,"X-Test","a\nb"],
                         [header,"Content-Length","1"],[header,"Host","x"],
                         [header,"Transfer-Encoding","chunked"],[header,"Connection","close"],
                         [body,"bad",[]],[body,"application/octet-stream",[256]],
                         [body,"application/octet-stream",[-1]],[timeout,0],[timeout,1.0Inf],
                         [redirect,maybe],['max-redirect',-1],[unknown,1]]),
           must_throw('http-request!'(get,URL,[Option],_),error(_,_))),
    forall(member(Options,[[[timeout,1],[timeout,2]],[[redirect,true],[redirect,false]],
                          [[header,"User-Agent","a"],[header,"user-agent","b"]]]),
           must_throw('http-request!'(get,URL,Options,_),error(domain_error(duplicate_http_option,_),_))),
    forall(member(Code,[0,1,10,13,31,127,256]),
           (string_codes(Value,[97,Code,98]),
            must_throw('http-request!'(get,URL,[[header,"X-Test",Value]],_),
                       error(domain_error(http_header_value,Value),_)))).

test(malformed_responses_become_http_errors) :-
    forall(member(Response,[[broken,7],['http-response',99,[],[]],
                           ['http-response',204,[],[1]],['http-response',200,[],[256]],
                           ['http-response',200,[["Content-Length","3"]],[]],
                           ['http-response',200,[["X-Test","a\rb"]],[]],
                           ['http-response',200,[["Content-Type","a/b"],["content-type","c/d"]],[]]]),
           (fixed(Response,Handler),with_server(Handler,error_response_case))).
error_response_case(_,URL) :-
    'http-request!'(get,URL,[],['http-response',Code,_,_]),assertion(Code==500).

test(endpoint_and_server_option_refusals) :-
    forall(member(Goal,['http-server-start!'("",0,x,[],_),
                        'http-server-start!'("127.0.0.1",65536,x,[],_),
                        'http-server-start!'("127.0.0.1",0,x,[[workers,0]],_),
                        'http-server-start!'("127.0.0.1",0,x,[[unknown,1]],_),
                        'http-server-stop!'([], _),'http-server-url'([bad],_),
                        'http-header'([[1,x]],"x",_),'http-header'([],"bad:name",_)]),
           must_throw(Goal,error(_,_))),
    'http-server-url'(['http-server',"::1",8000,0],IPv6),assertion(IPv6=="http://[::1]:8000/").

:- end_tests(lib_http).
