% Purpose: check every encoding against the host's own and against its round trip
% over generated bytes and text, and check the refusals for input that is not what
% it claims to be.
% Guarantees: every encoding round-trips over generated inputs, UTF-8 is the host's
% own bytes for the same text, hex is lower case and case-insensitive, base64 is
% RFC 4648 in both alphabets against the host's own encoder, and a byte that is not
% one is refused naming it [tested: lib_encoding; commit=WORKTREE].
% Owns resources: none; every value is a term.

:- ensure_loaded('../../../../engine/qlf_boot.pl').
:- ensure_loaded('../../../../engine/metta.pl').
:- use_module(library(lists), [member/2, nth1/3, numlist/3]).
:- use_module(library(apply), [maplist/2, maplist/3]).
:- use_module(library(yall), [(>>)/3]).
:- use_module(library(base64), [base64_encoded/3]).
:- use_module(library(random), [random_between/3]).
:- initialization(consult('../../lib/lib_encoding/lib_encoding.pl')).

:- begin_tests(lib_encoding).
:- meta_predicate must_throw(0, ?).

must_throw(Goal, Expected) :-
    catch(Goal, Error, true), assertion(nonvar(Error)), assertion(Error = Expected).

random_bytes(Bytes) :-
    random_between(0, 12, Length),
    length(Bytes, Length),
    maplist([Byte]>>random_between(0, 255, Byte), Bytes).

random_text(Text) :-
    random_between(0, 10, Length),
    length(Codes, Length),
    maplist([Code]>>( random_between(1, 6, Which),
                      nth1(Which, [0'a, 0'Z, 0'é, 0x6F22, 0x1F642, 0' ], Code) ),
            Codes),
    string_codes(Text, Codes).

% Every encoding is a bijection on what it accepts, which is the one law all three
% owe: bytes to text to the same bytes, and text to bytes to the same text.
test(every_encoding_round_trips) :-
    set_random(seed(20260912)),
    forall(between(1, 300, _),
           ( random_bytes(Bytes),
             'hex-encode'(Bytes, Hex), 'hex-decode'(Hex, FromHex),
             assertion(FromHex == Bytes),
             forall(member(Alphabet, [standard, url]),
                    ( 'base64-encode'(Alphabet, Bytes, Text),
                      'base64-decode'(Alphabet, Text, FromBase64),
                      assertion(FromBase64 == Bytes) )),
             random_text(String),
             'utf8-encode'(String, TextBytes), 'utf8-decode'(TextBytes, Again),
             assertion(Again == String) )).

% UTF-8 is the host's own encoding of the same text, byte for byte, which is what
% makes the byte count a length in bytes: the differential is against the host's
% own conversion through a memory file.
test(utf8_is_the_hosts_own_encoding) :-
    set_random(seed(20260912)),
    forall(between(1, 200, _),
           ( random_text(Text),
             'utf8-encode'(Text, Bytes),
             host_utf8_bytes(Text, Expected),
             assertion(Bytes == Expected) )),
    'utf8-encode'("é", Accented), assertion(Accented == [195, 169]),
    'utf8-encode'("漢", Wide), assertion(Wide == [230, 188, 162]),
    'utf8-encode'("🙂", Emoji), assertion(Emoji == [240, 159, 153, 130]),
    string_codes("🙂", [Code]), assertion(Code > 255).

% The host's own text-to-bytes, through the encoding a stream does it with.
host_utf8_bytes(Text, Bytes) :-
    setup_call_cleanup(new_memory_file(File),
                       ( setup_call_cleanup(open_memory_file(File, write, Out, [encoding(utf8)]),
                                            format(Out, '~w', [Text]),
                                            close(Out)),
                         setup_call_cleanup(open_memory_file(File, read, In, [encoding(octet)]),
                                            read_string(In, _, Read),
                                            close(In)),
                         string_codes(Read, Bytes) ),
                       free_memory_file(File)).

% Hex is lower case out and either case in, two digits a byte, which is what a hash
% and a wire dump are written as.
test(hex_answers_lower_case_and_reads_either) :-
    'hex-encode'([0, 15, 16, 255], Text),
    assertion(Text == "000f10ff"),
    'hex-decode'("000F10FF", Upper), assertion(Upper == [0, 15, 16, 255]),
    'hex-decode'("000f10ff", Lower), assertion(Lower == [0, 15, 16, 255]),
    forall(between(0, 255, Byte),
           ( 'hex-encode'([Byte], Digits),
             string_length(Digits, 2),
             'hex-decode'(Digits, [Byte]) )),
    'hex-encode'([], Empty), assertion(Empty == ""),
    'hex-decode'("", None), assertion(None == []).

% base64 against the host's own encoder over the same bytes, in both alphabets, and
% the two RFC 4648 spellings where they differ.
test(base64_is_the_hosts_own_encoding) :-
    set_random(seed(20260912)),
    forall(between(1, 200, _),
           ( random_bytes(Bytes),
             string_codes(Plain, Bytes),
             'base64-encode'(standard, Bytes, Standard),
             base64_encoded(Plain, ExpectedStandard,
                            [padding(true), charset(classic), as(string), encoding(iso_latin_1)]),
             assertion(Standard == ExpectedStandard),
             'base64-encode'(url, Bytes, Url),
             base64_encoded(Plain, ExpectedUrl,
                            [padding(false), charset(url), as(string), encoding(iso_latin_1)]),
             assertion(Url == ExpectedUrl) )),
    % The two alphabets differ exactly in the two characters RFC 4648 names.
    'base64-encode'(standard, [255, 254, 253], Standard),
    assertion(Standard == "//79"),
    'base64-encode'(url, [255, 254, 253], Url), assertion(Url == "__79"),
    'base64-encode'(standard, [104], Padded), assertion(Padded == "aA=="),
    'base64-encode'(url, [104], Unpadded), assertion(Unpadded == "aA"),
    % Padding is what the standard alphabet has and the url one does not, so the
    % standard text of any length is a multiple of four characters.
    forall(between(0, 8, Length),
           ( bytes_of_length(Length, Bytes2), 'base64-encode'(standard, Bytes2, Text),
             string_length(Text, TextLength), assertion(TextLength mod 4 =:= 0) )).

% numlist/3 fails for an empty range rather than answering the empty list, which is
% the trap every generator in these suites meets.
bytes_of_length(0, []) :- !.
bytes_of_length(Length, Bytes) :- numlist(1, Length, Bytes).

% Every refusal, and what each one names.
test(a_value_that_is_not_a_byte_is_refused_by_name) :-
    forall(member(Goal, ['hex-encode'([256], _), 'base64-encode'(standard, [256], _),
                         'utf8-decode'([256], _)]),
           must_throw(Goal, error(type_error(byte, 256), _))),
    forall(member(Goal, ['hex-encode'([two], _), 'utf8-decode'([1, two], _)]),
           must_throw(Goal, error(type_error(byte, two), _))),
    must_throw('hex-encode'(notalist, _), error(type_error(list, notalist), _)),
    must_throw('hex-encode'([-1], _), error(type_error(byte, -1), _)),
    % A code point that fits in a byte IS one, which is why the two are worth
    % telling apart at all.
    string_codes("é", Codes), 'hex-encode'(Codes, Accented),
    assertion(Accented == "e9").

test(malformed_text_is_refused_by_name) :-
    must_throw('hex-decode'("abc", _), error(domain_error(hex_text, "abc"), _)),
    must_throw('hex-decode'("zz", _), error(domain_error(hex_digit, z), _)),
    must_throw('hex-decode'("0g", _), error(domain_error(hex_digit, g), _)),
    must_throw('utf8-decode'([255], _), error(domain_error(utf8_bytes, [255]), _)),
    must_throw('utf8-decode'([195], _), error(domain_error(utf8_bytes, [195]), _)),
    must_throw('base64-decode'(standard, "not base64!", _),
               error(domain_error(base64_text, "not base64!"), _)),
    must_throw('base64-encode'(nosuch, [1], _),
               error(domain_error(base64_alphabet, nosuch), _)),
    catch('base64-encode'(nosuch, [1], _), error(_, context(_, Alphabets)), true),
    assertion(Alphabets == [standard, url]),
    must_throw('hex-decode'(7, _), error(type_error(string, 7), _)),
    must_throw('base64-decode'(standard, 7, _), error(type_error(string, 7), _)).

:- end_tests(lib_encoding).
