% Purpose: verify UUID name vectors, generated byte round trips, layout properties
% and validation/refusal boundaries through the public library heads.
% Guarantees: standard ASCII names agree with the host, complete names agree with
% CPython vectors, and each byte value occurs at each position in the round trips.
% [tested: lib_uuid; commit=d5de00cc183b4b395b552f3aae7fca87752ef38c].

:- ensure_loaded('../../../../engine/qlf_boot.pl').
:- ensure_loaded('../../../../engine/metta.pl').
:- use_module(library(uuid), [uuid/2]).
:- use_module(library(lists), [member/2, nth0/3]).
:- initialization(consult('../../lib/lib_uuid/lib_uuid.pl')).

:- begin_tests(lib_uuid).
:- meta_predicate must_throw(0, ?).

must_throw(Goal, Expected) :-
    catch(Goal, Error, true), assertion(nonvar(Error)), assertion(Error = Expected).

test(generated_versions_and_timestamp) :-
    forall(between(1, 32, _),
           ( 'uuid-random!'(Random), 'uuid-version'(Random, Version),
             'uuid-variant'(Random, Variant), 'uuid-is'(Random, Valid),
             assertion(Version == 4), assertion(Variant == rfc), assertion(Valid == true),
             assertion(\+ 'uuid-timestamp'(Random, _)) )),
    get_time(Before), 'uuid-time!'(Time), get_time(After),
    'uuid-version'(Time, TimeVersion), assertion(TimeVersion == 1),
    'uuid-timestamp'(Time, Stamp), assertion(Stamp >= Before), assertion(Stamp =< After),
    'uuid-timestamp'("13814000-1dd2-11b2-8000-000000000000", Epoch),
    assertion(Epoch =:= 0),
    'uuid-timestamp'("13814001-1dd2-11b2-8000-000000000000", Tick),
    assertion(Tick =:= 0.0000001),
    assertion(\+ 'uuid-timestamp'("13814000-1dd2-21b2-8000-000000000000", _)).

test(standard_names_agree_with_ossp) :-
    'uuid-namespaces'(Namespaces), assertion(Namespaces == [dns,url,oid,x500]),
    forall((member(Version,[3,5]), member(Namespace,Namespaces),
            member(Name,["", "example.com", "1.2.840.113549", "cn=Test", "a/b?c=d"])),
           ( atom_string(Atom, Name), Option =.. [Namespace,Atom],
             uuid(ExpectedAtom,[version(Version),Option]), atom_string(ExpectedAtom,Expected),
             'uuid-name'(Version,Namespace,Name,Actual), assertion(Actual == Expected) )).

% The independent oracle is CPython 3.14's uuid3/uuid5 over complete UTF-8 names.
% https://github.com/python/cpython/blob/v3.14.0/Lib/uuid.py#L763-L790
name_vector([97,0,98], "002a0ada-f547-375a-bab5-896a11d1927e",
                         "0a63f66b-e02f-5d2d-9fd4-aad819cf5352").
name_vector([233], "3a356d77-46a8-3ec1-8205-b80596740632",
                   "ebfe0af8-3997-5ade-b634-ba92cf69f557").
name_vector([0x6f22], "1f9d873c-79c5-37f3-a181-6bab16c1f1c9",
                      "bc69bd8f-e209-57d6-b4e1-93ba24e6c41d").

test(complete_utf8_names_and_custom_namespaces) :-
    forall(name_vector(Codes,MD5,SHA1),
           ( string_codes(Name,Codes),
             'uuid-name'(3,dns,Name,V3), assertion(V3 == MD5),
             'uuid-name'(5,dns,Name,V5), assertion(V5 == SHA1) )),
    'uuid-name'(5,"6BA7B810-9DAD-11D1-80B4-00C04FD430C8","example.com",Named),
    assertion(Named == "cfbff0d1-9375-5685-968c-48ce8b15ae17"),
    'uuid-name'(5,Named,"leaf",First), 'uuid-name'(5,Named,"leaf",Again),
    assertion(First == Again),
    'uuid-name'(5,Named,"other",Other), assertion(First \== Other).

test(generated_bytes_round_trip_every_position) :-
    forall(between(0,255,Seed),
           ( findall(Byte,(between(0,15,Index),Byte is (Seed+Index*17) mod 256),Bytes),
             'uuid-of-bytes'(Bytes,UUID), 'uuid-bytes'(UUID,Again),
             assertion(Again == Bytes), 'uuid-is'(UUID,Valid), assertion(Valid == true),
             string_upper(UUID,Upper), 'uuid-bytes'(Upper,FromUpper),
             assertion(FromUpper == Bytes),
             'uuid-version'(UUID,V), nth0(6,Bytes,VB), assertion(V =:= VB >> 4) )).

test(nil_and_variant_boundaries) :-
    'uuid-nil'(Nil), assertion(Nil == "00000000-0000-0000-0000-000000000000"),
    'uuid-version'(Nil,V), assertion(V == 0),
    'uuid-variant'(Nil,Ncs), assertion(Ncs == ncs),
    assertion(\+ 'uuid-timestamp'(Nil,_)),
    forall(member(Byte-Variant,[0-ncs,127-ncs,128-rfc,191-rfc,
                               192-microsoft,223-microsoft,224-future,255-future]),
           ( Bytes=[0,0,0,0,0,0,0,0,Byte,0,0,0,0,0,0,0],
             'uuid-of-bytes'(Bytes,UUID), 'uuid-variant'(UUID,Actual),
             assertion(Actual == Variant) )).

test(validation_rejects_every_nonhex_mutation) :-
    Base="cfbff0d1-9375-5685-968c-48ce8b15ae17",
    forall(between(0,35,Index),
           ( sub_string(Base,0,Index,_,Prefix), Start is Index+1,
             sub_string(Base,Start,_,0,Suffix), atomics_to_string([Prefix,"g",Suffix],Bad),
             'uuid-is'(Bad,Valid), assertion(Valid == false) )),
    forall(member(Bad,["", "------------------------------------", "cfbff0d193755685968c48ce8b15ae17",
                       "cfbff0d1--9375-5685-968c-48ce8b15ae17",7,Base-Base]),
           ('uuid-is'(Bad,Valid),assertion(Valid == false))),
    string_codes(Nul,[0]), string_concat(Base,Nul,WithNul),
    'uuid-is'(WithNul,False), assertion(False == false).

test(delimiters_are_literal_hyphens) :-
    'uuid-nil'(Base), string_codes(Nul,[0]),
    forall(member(Index,[8,13,18,23]),
           ( sub_string(Base,0,Index,_,Prefix), Start is Index+1,
             sub_string(Base,Start,_,0,Suffix), atomics_to_string([Prefix,Nul,Suffix],Bad),
             'uuid-is'(Bad,Valid), assertion(Valid == false),
             must_throw('uuid-bytes'(Bad,_),error(domain_error(uuid,Bad),_)) )).

test(refusals_name_the_invalid_input_and_repair) :-
    forall(member(Head,['uuid-bytes','uuid-version','uuid-variant','uuid-timestamp']),
           ( Goal=..[Head,"bad",_], must_throw(Goal,error(domain_error(uuid,"bad"),context(Head,_))) )),
    forall(member(Version,[1,2,4,6,3.0]),
           must_throw('uuid-name'(Version,dns,"x",_),error(domain_error(uuid_name_version,Version),_))),
    must_throw('uuid-name'(5,missing,"x",_),error(domain_error(uuid_namespace,missing),_)),
    must_throw('uuid-name'(5,"bad","x",_),error(domain_error(uuid,"bad"),_)),
    must_throw('uuid-name'(5,dns,7,_),error(type_error(string,7),_)),
    must_throw('uuid-of-bytes'([1,2],_),error(domain_error(uuid_bytes,[1,2]),_)),
    must_throw('uuid-of-bytes'([256],_),error(type_error(between(0,255),256),_)),
    must_throw('uuid-of-bytes'([-1],_),error(type_error(between(0,255),-1),_)).

:- end_tests(lib_uuid).
