#!/bin/sh
# Purpose: write down which host-workaround patches a SWI-Prolog carries, in
#   the one shape the engine's boot check reads, so a patched host can be
#   told from a stock one by something other than its version string.
#
# Usage:
#   declare-host.sh require            print engine/host_patches.pl: every
#                                      patch this tree carries, the set the
#                                      engine refuses to boot without
#   declare-host.sh declare SRC HOME   write HOME/metta-host.pl: the patches
#                                      the source tree SRC carries, for a
#                                      host installed from SRC into HOME
#
# Both write host_patch(File, Sha256) facts, one per patch, so the check
# compares two sets of identical terms. The digest is of the patch file, which
# makes a host built from an OLDER version of a patch fail the same way a
# stock host does rather than passing on its name.
#
# `declare` also writes host_build(CompiledAt), the compiled_at flag of the
# launcher installed in HOME, because the C patches live in the binary and the
# declaration lives in the home, and SWI_HOME_DIR can put any binary in front
# of any home: the venv here exports it to every process, and a stock
# /usr/bin/swipl started under it reports the patched home and would read its
# declaration [measured 2026-09-23: home=/home/user/Dev/swipl-patched/lib/swipl
# with compiled_at 'Aug 30 2026, 09:21:19', the patched build's being
# 'Sep 16 2026, 22:48:43'].
#
# Why a declaration at all: /usr/bin/swipl and the patched build both report
# "SWI-Prolog version 10.1.14 for x86_64-linux", so the version cannot tell
# them apart, and the reproductions that can are separate processes a boot
# cannot afford [measured 2026-09-23: both --version lines identical].
#
# Assumes: git and sha256sum on PATH; SRC is the swipl-devel tree HOME was
#   installed from, with its patches applied in the working tree the way
#   fetch-source.sh leaves them.
# Guarantees:
#   - `require` lists every tests/checks/host_workarounds/*.patch in name order
#     and nothing else, so engine/host_patches.pl is a function of that
#     directory [tested: tests/checks/check_host_declaration.py; commit=WORKTREE]
#   - `declare` lists a patch exactly when `git apply --reverse --check`
#     succeeds for it in the tree patch-root.sh routes it to, so a patch the
#     tree lacks is absent from the declaration and the engine names it
#     [tested: tests/checks/check_host_declaration.py; commit=WORKTREE]
#   - `declare` records the compiled_at of HOME/bin/<arch>/swipl, read with
#     SWI_HOME_DIR unset so the answer is that binary's own, and refuses when
#     HOME holds no launcher to read it from
#   - the declaration is replaced whole, by rename, so a reader never sees a
#     half-written one
#   - `declare` exits 1 when the tree lacks any patch, after writing the
#     declaration, so a build stops where a half-patched host would otherwise
#     reach a wheel, and the file still names exactly what the engine will
#     refuse [tested: tests/checks/check_host_declaration.py; commit=WORKTREE]
# Fails when: SRC is not a git tree, or HOME does not exist; both refuse with
#   exit 1 rather than writing a declaration nothing was checked against.
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(CDPATH= cd -- "$HERE/../.." && pwd)
PATCHES="$ROOT/tests/checks/host_workarounds"
. "$HERE/patch-root.sh"

fact() {
    printf "host_patch('%s', '%s').\n" "$(basename "$1")" \
        "$(sha256sum "$1" | cut -d' ' -f1)"
}

case "${1:-}" in
    require)
        cat <<'HEADER'
% Purpose: the host-workaround patches this engine refuses to boot without,
%   one host_patch(File, Sha256) fact per tests/checks/host_workarounds/*.patch.
% Generated by `sh tools/pymetta-host/declare-host.sh require`; the
%   host-declaration lane regenerates it and fails on any difference, so edit
%   the patches and rerun the command rather than this file.
:- module(metta_host_patches, [host_patch/2]).

HEADER
        for patch in "$PATCHES"/*.patch; do fact "$patch"; done
        ;;
    declare)
        [ $# -eq 3 ] || { echo "usage: declare-host.sh declare SRC HOME" >&2; exit 2; }
        SRC=$2; HOME_DIR=$3
        git -c safe.directory='*' -C "$SRC" rev-parse --git-dir >/dev/null 2>&1 || {
            printf 'declare-host: %s is not a git tree, so nothing says which patches it carries\n' \
                "$SRC" >&2; exit 1; }
        [ -d "$HOME_DIR" ] || {
            printf 'declare-host: %s does not exist; install the host first\n' "$HOME_DIR" >&2
            exit 1; }
        LAUNCHER=$(ls "$HOME_DIR"/bin/*/swipl 2>/dev/null | head -1)
        [ -n "$LAUNCHER" ] || {
            printf 'declare-host: no launcher under %s/bin/<arch>/, so nothing says which build this home belongs to\n' \
                "$HOME_DIR" >&2; exit 1; }
        BUILT=$(env -u SWI_HOME_DIR "$LAUNCHER" -q \
            -g 'current_prolog_flag(compiled_at, C), write(C)' -t halt < /dev/null)
        [ -n "$BUILT" ] || { printf 'declare-host: %s reported no compiled_at\n' "$LAUNCHER" >&2; exit 1; }
        OUT="$HOME_DIR/metta-host.pl"
        {
            echo "% The host-workaround patches this SWI-Prolog was built with, written by"
            echo "% tools/pymetta-host/declare-host.sh from the tree it was installed from."
            echo "% The engine refuses to boot unless the running build is the one named"
            echo "% here and every patch it requires is listed with the same sha256."
            printf "host_build('%s').\n" "$BUILT"
        } > "$OUT.$$"
        carried=0; missing=''
        for patch in "$PATCHES"/*.patch; do
            if root=$(patch_root "$SRC" "$patch") &&
               git -c safe.directory='*' -C "$root" apply --reverse --check "$patch" 2>/dev/null; then
                fact "$patch" >> "$OUT.$$"
                carried=$((carried + 1))
            else
                missing="$missing $(basename "$patch" .patch)"
            fi
        done
        mv "$OUT.$$" "$OUT"
        total=$(ls "$PATCHES"/*.patch | wc -l)
        printf 'declare-host: %s carries %s of %s patch(es)%s\n' "$SRC" "$carried" \
            "$total" "${missing:+; missing:$missing}" >&2
        [ -z "$missing" ]
        ;;
    *)
        echo "usage: declare-host.sh require | declare SRC HOME" >&2
        exit 2
        ;;
esac
