# Purpose: the settings a host embedding the engine applies before the engine
#   loads, as shell variables, which tools/run.sh sources and passes to swipl
#   as --<flag>=<value>, so the launcher boots under the bounds the seats
#   declare rather than a number of its own.
# Assumes: each block below is one Setting in
#   extensions/python/metta/_catalog/bounds.py that names the SWI flag it
#   sets.
# Guarantees:
#   - this file is GENERATED by extensions/python/tools/boundsgen.py from
#     those declarations, beside extensions/cmetta/settings.h; edit the
#     declaration and rerun the tool with --write, never this file, and the
#     tool's check fails on any drift [tested:
#     test_each_declaration_projection_refuses_an_independent_edit;
#     commit=13d61d9b4b803c45609bd6ddc17ec5ba5048b216]
#   - for a setting <name>, MT_<NAME>_FLAG is the SWI flag it sets,
#     MT_<NAME>_ENVIRONMENT the environment variable whose value replaces its
#     default, present when the declaration names one, and MT_<NAME>_DEFAULT
#     the default in the flag's own unit, the C header's three names [tested:
#     test_setting_declaration_reaches_every_projection; commit=13d61d9b4b803c45609bd6ddc17ec5ba5048b216]
# Open Obligations: None.

# stack_limit: Maximum SWI stack size in bytes.
MT_STACK_LIMIT_FLAG=stack_limit
MT_STACK_LIMIT_ENVIRONMENT=METTA_STACK_LIMIT
MT_STACK_LIMIT_DEFAULT=8000000000
